proyecto/floreria/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include(('generales.urls','generales'),namespace='generales')),
    path('productos/',include(('productos.urls','productos'),namespace='productos')),
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
	    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/generales/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from generales.views import Home, HomeSinPrivilegios

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='generales/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='generales/login.html'), name='logout'),
    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),
]

proyecto/productos/urls.py
from django.urls import path

from productos.views import ProductoView, ProductoNew, ProductoEdit, ProductoDel, Galeria

urlpatterns = [
    path('productos', ProductoView.as_view(), name='producto_list'),
    path('productos/new', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/delete/<int:pk>', ProductoDel.as_view(), name='producto_delete'),
    path('productos/galeria', Galeria.as_view(), name='galeria'),
]

proyecto/generales/models.py
from django.db import models

# Create your models here.

class ClaseModelo(models.Model):
    activo = models.BooleanField(default=True)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

proyecto/productos/models.py
from django.db import models

from generales.models import ClaseModelo
# Create your models here.

class Producto(ClaseModelo):
    fotografia = models.ImageField(upload_to="img")
    nombre = models.CharField(max_length=20)
    valor = models.IntegerField()
    descripcion = models.TextField(max_length=100)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Productos"

proyecto/productos/forms.py
from django import forms

from productos.models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['fotografia','nombre','valor','descripcion','activo','stock']
        labels = {'fotografia': "Fotografía del producto",
                  'nombre': "Nombre del producto", 
                  'valor' : "Valor del producto", 
                  'descripcion' : "Descripción del producto", 
                  'activo' : "Estado del producto", 
                  'stock' : "Stock del producto"}
        widget = {'fotografia': forms.FileInput(), 
                  'nombre': forms.TextInput(), 
                  'valor': forms.NumberInput(),
                  'descripcion': forms.TextInput(), 
                  'activo': forms.CheckboxInput(), 
                  'stock': forms.NumberInput()}

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

proyecto/generales/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.views import generic

# Create your views here.
class SinPrivilegios(PermissionRequiredMixin):
    login_url = 'generales:sin_privilegios'
    raise_exception = False
    redirect_field_name = "redirecto_to"

    def handle_no_permission(self):
        return HttpResponseRedirect(reverse_lazy(self.login_url))

class Home(generic.TemplateView):
    template_name='generales/home.html'

class HomeSinPrivilegios(generic.TemplateView):
    template_name="generales/sin_privilegios.html"

proyecto/productos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from productos.models import Producto
from productos.forms import ProductoForm
from generales.views import SinPrivilegios

# Create your views here.

class ProductoView(LoginRequiredMixin,SinPrivilegios,generic.ListView):
    permission_required = "producto.view_producto"
    model = Producto
    template_name = "productos/producto_list.html"
    context_object_name = "obj"
    login_url = 'generales:login'

class ProductoNew(SuccessMessageMixin,LoginRequiredMixin,SinPrivilegios,generic.CreateView):
    permission_required = "producto.add_producto"
    model = Producto
    template_name = "productos/producto_form.html"
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy("productos:producto_list")
    login_url = 'generales:login'
    success_message = "Producto creado correctamente"

class ProductoEdit(SuccessMessageMixin,LoginRequiredMixin,SinPrivilegios,generic.UpdateView):
    permission_required = "producto.change_producto"
    model = Producto
    template_name = "productos/producto_form.html"
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy("productos:producto_list")
    login_url = 'generales:login'
    success_message = "Producto modificado correctamente"

class ProductoDel(LoginRequiredMixin,SinPrivilegios,generic.DeleteView):
    permission_required = "producto.delete_producto"
    model = Producto
    template_name = "productos/producto_del.html"
    context_object_name = 'obj'
    success_url = reverse_lazy("productos:producto_list")
    login_url = 'generales:login'

class Galeria(generic.ListView):
    model = Producto
    template_name = "productos/galeria.html"
    context_object_name = "obj"

proyecto/generales/templates/generales/home.html
{% extends 'base/base.html' %}

proyecto/generales/templates/generales/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login - Pétalos</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'base/css/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'base/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'base/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Iniciar Sesión</h3>
                        <small class="text-danger">
                            {% if form.errors %}
                                {% for field in form %}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            {{ error|escape }}
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                                {% if form.non_field_errors%}
                                    {% for error in form.non_field_errors %}
                                        {{ error|escape }}
                                    {% endfor %}
                                {% endif %}
                            {% endif %}
                        </small>
                    </div>
                    <div class="panel-body">
                        <form method="POST">
                            {% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Usuario" name="username" type="text" id="id_username" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Contraseña" name="password" type="password" id="id_password" value="">
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-lg btn-success btn-block">Acceder</button>
                                <a href="{% url 'generales:home' %}" class="btn btn-lg btn-warning btn-block">Regresar</a>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

   <!-- jQuery -->
   <script src="{% static 'base/js/jquery.min.js' %}"></script>

   <!-- Bootstrap Core JavaScript -->
   <script src="{% static 'base/js/bootstrap.min.js' %}"></script>

   <!-- Metis Menu Plugin JavaScript -->
   <script src="{% static 'base/js/metisMenu.min.js' %}"></script>

   <!-- Custom Theme JavaScript -->
   <script src="{% static 'base/js/sb-admin-2.js' %}"></script>

</body>

</html>

proyecto/generales/templates/generales/sin_privilegios.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
  {% block titulo %}
  Florería - DWY
  {% endblock titulo %}
  </title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'base/css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'base/css/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'base/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'base/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Datatable-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/r-2.2.3/datatables.min.css"/>
    
     <!-- XDSoft DateTimePicker -->  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />      
</head>

<body>
<div class="container">
    
        <div class="panel panel-primary">
            <div class="panel-heading">
                Sin privilegios necesarios
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h4 class="text-danger text-center">Tu Usuario
                            <mark>no tiene suficientes privilegios</mark> para cargar opción solicitada.
                            <br>
                            <small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios.</small>
                        </h4>
                        <br>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                    <a href="{% url 'generales:logout' %}" class="btn btn-warning">
                        <span class="fas fa-user-secret"></span> Volver</a>
            </div>
        </div>
    
</div>
  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Javier Paredes DWY4101 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- jQuery -->
    <script src="{% static 'base/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'base/js/metisMenu.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'base/js/sb-admin-2.js' %}"></script>

    <!-- Datatable-->
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/r-2.2.3/datatables.min.js"></script>
</body>

</html>

proyecto/productos/templates/productos/galeria.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
  {% block titulo %}
  Florería - DWY
  {% endblock titulo %}
  </title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'base/css/one-page-wonder.min.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'generales:home' %}">Pétalos - Tienda Online</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'generales:home' %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Galería</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:producto_list' %}">Formulario de Productos</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Galería de Productos</h1>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>

<!-- List productos -->
{% for item in obj %}
<section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{{ item.fotografia.url }}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">{{ item.nombre }}</h2>
            <p>{{ item.descripcion }}</p>
            <p>Precio: ${{ item.valor }}</p>
            <p>Stock disponible: {{ item.stock }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endfor %}


  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Javier Paredes DWY4101 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

proyecto/productos/templates/productos/producto_list.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
  {% block titulo %}
  Florería - DWY
  {% endblock titulo %}
  </title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'base/css/one-page-wonder.min.css' %}" rel="stylesheet">

<!-- Bootstrap Core CSS -->
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'base/css/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'base/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'base/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Datatable-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/r-2.2.3/datatables.min.css"/>
    
     <!-- XDSoft DateTimePicker -->  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" /> 
</head>

<body>
<header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Listado de Productos</h1>
        <a href="{% url 'generales:logout' %}" class="btn btn-primary btn-xl rounded-pill mt-5"><i class="fa fa-sign-out fa-fw"></i> ¿Cerrar sesión de {{ user.username}} ?</a>
        <a href="{% url 'generales:home' %}" class="btn btn-primary btn-xl rounded-pill mt-5"><i class="fa fa-sign-out fa-fw"></i> Salir y no cerrar sesión de {{ user.username}}</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>

  <div class="panel panel-primary">
    <div class="panel-heading">
        <a href="{% url 'productos:producto_new' %}" class="btn btn-info"><span class="fa fa-plus-circle"></span> Nuevo</a>
        <a href="#" target="print" class="btn btn-warning"><span class="fa fa-print"></span> Imprimir</a>
    </div>
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Fotografia</th>
                    <th>Nombre</th>
                    <th>Valor</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Stock</th>
                    <th>Creado</th>
                    <th>Modificado</th>
                    <th class="all">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td> <!--  imprime-->
                    <td>{{ item.fotografia }}</td>
                    <td>{{ item.nombre }}</td>
                    <td>{{ item.valor }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.activo|yesno:"Activo,Inactivo" }}</td>
                    <td>{{ item.stock }}</td>
                    <td>{{ item.creado|date:'d/m/Y H:i' }}</td>
                    <td>{{ item.modificado|date:'d/m/Y H:i' }}</td>
                    <td>
                        <a href="{% url 'productos:producto_edit' item.id %}" class="btn btn-primary btn-circle"><span class="fa fa-edit"></span></a>
                        <a href="{% url 'productos:producto_delete' item.id %}" class="btn btn-danger btn-circle"><span class="fa fa-trash"></span></a>
                        <a href="#" target="print" class="btn btn-default btn-circle">
                            <span class="fa fa-print"></span>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <h1 class="page-header">
                                <small class="text-danger text-center">
                                    {% if messages %}
                                        {% for message in messages %}
                                            {{ message|safe}}<br>
                                        {% endfor %}
                                    {% endif %}
                                </small>
                            </h1>
    </div>
</div>

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Javier Paredes DWY4101 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- jQuery -->
    <script src="{% static 'base/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'base/js/metisMenu.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'base/js/sb-admin-2.js' %}"></script>

    <!-- Datatable-->
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/r-2.2.3/datatables.min.js"></script>

    <script>
        $(document).ready( function () {
            $('#dataTables-example').DataTable(
                            {
                responsive: true
            }
            );
        } );
    </script>
</body>

</html>

proyecto/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
  {% block titulo %}
  Florería - DWY
  {% endblock titulo %}
  </title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'base/css/one-page-wonder.min.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'generales:home' %}">Pétalos - Tienda Online</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'generales:home' %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:galeria' %}">Galería</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:producto_list' %}">Formulario de Productos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/oauth/login/facebook/">Login con Facebook</a>
          </li>
          <li>
             <a class="nav-link">Bienvenido {{ user.username }}</a>
        </li>
        </ul>
      </div>
    </div>
  </nav>

  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Florería Pétalos</h1>
        <h2 class="masthead-subheading mb-0">Visita nuestra galería</h2>
        <a href="{% url 'productos:galeria' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Ir a galería</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'base/img/girasol.jpg' %}" alt="girasol">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Girasoles</h2>
            <p>El girasol es el símbolo del Sol y simboliza el amor y la admiración. Pero también la felicidad, la vitalidad, el positivismo y la energía. En la cultura china simboliza una larga vida y buena suerte.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'base/img/rosas.jpg' %}" alt="rosas">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-5">
            <h2 class="display-4">Rosas</h2>
            <p>Están reservadas para la pareja o persona que ocupa nuestro corazón. Además de amor, las rosas rojas también representan la pasión.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="{% static 'base/img/hortensias.jpg' %}" alt="hortensias">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Hortensias</h2>
            <p>Las hortensias son flores que, según diferentes versiones, proceden de América o de Extremo Oriente. Sus hojas ovaladas y terminadas en punta, son de gran tamaño, y tienen un intenso color verde, que al llegar el otoño, se marchitan y caen.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Javier Paredes DWY4101 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>